export const exclusive = [
  {
    id: 1,
    image: "https://seagm-media.seagmcdn.com/icon_400/626.jpg",
    title: "iTunes Gift Card 1000 SEK SE",
    subtitle: "iTunes Gift Card (SE)",
    percent: "-1.0",
  },
  {
    id: 2,
    image: "https://seagm-media.seagmcdn.com/icon_400/84.jpg",
    title: "Star Wars: 2400 Cartel Coin (Global)",
    subtitle: "star wars: The Old Repulic (GLOBAL)",
    percent: "-5.0",
  },
  {
    id: 3,
    image: "https://seagm-media.seagmcdn.com/icon_400/626.jpg",
    title: "iTunes Gift Card 4 EURO DE",
    subtitle: "iTunes Gift Card (DE)",
    percent: "-1.5",
  },
  {
    id: 4,
    image: "https://seagm-media.seagmcdn.com/icon_400/402.jpg",
    title: "Steam Wallet Code 1000 HK Global",
    subtitle: "Steam Wallet Code (HKD)",
    percent: "-3.0",
  },
  {
    id: 5,
    image: "https://seagm-media.seagmcdn.com/icon_400/626.jpg",
    title: "iTunes Gift Card 4 EURO BE",
    subtitle: "iTunes Gift Card (BE)",
    percent: "-1.5",
  },
  {
    id: 1,
    image: "https://seagm-media.seagmcdn.com/icon_400/626.jpg",
    title: "iTunes Gift Card 1000 SEK SE",
    subtitle: "iTunes Gift Card (SE)",
    percent: "-1.0",
  },
  {
    id: 2,
    image: "https://seagm-media.seagmcdn.com/icon_400/84.jpg",
    title: "Star Wars: 2400 Cartel Coin (Global)",
    subtitle: "star wars: The Old Repulic (GLOBAL)",
    percent: "-5.0",
  },
  {
    id: 3,
    image: "https://seagm-media.seagmcdn.com/icon_400/626.jpg",
    title: "iTunes Gift Card 4 EURO DE",
    subtitle: "iTunes Gift Card (DE)",
    percent: "-1.5",
  },
  {
    id: 4,
    image: "https://seagm-media.seagmcdn.com/icon_400/402.jpg",
    title: "Steam Wallet Code 1000 HK Global",
    subtitle: "Steam Wallet Code (HKD)",
    percent: "-3.0",
  },
  {
    id: 5,
    image: "https://seagm-media.seagmcdn.com/icon_400/626.jpg",
    title: "iTunes Gift Card 4 EURO BE",
    subtitle: "iTunes Gift Card (BE)",
    percent: "-1.5",
  },
];
